# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_convolve <- function(a, b) {
    .Call(`_flexpolyline_cpp_convolve`, a, b)
}

cpp_decode <- function(encoded) {
    .Call(`_flexpolyline_cpp_decode`, encoded)
}

cpp_encode <- function(line) {
    .Call(`_flexpolyline_cpp_encode`, line)
}

