# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_decode <- function(encoded) {
    .Call(`_flexpolyline_cpp_decode`, encoded)
}

cpp_encode <- function(line, precision, third_dim, third_dim_precision) {
    .Call(`_flexpolyline_cpp_encode`, line, precision, third_dim, third_dim_precision)
}

